version: '2'

services:
  test:
    build: backend
    command: ./wait-for testdb:5432 -- npm run test:xunit
    environment:
      DATABASE_URL: postgres://example:example@testdb/example
      OUTPUT: /results/test-results.xml
    depends_on:
      - testdb
    volumes:
      - ./results/mocha:/results

  testdb:
    image: postgres:9.4
    environment:
      POSTGRES_DB: example
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
    volumes:
      - testdbdata:/var/lib/postgresql/data

volumes:
  testdbdata: